### ISSUE TITLE
能留个联系方式交流下吗

### ISSUE THREAD

**Issue by JiachengDang** [shaoniana1997/Paper-Notes#1]
看到你做了很多image emotion的东西，想问几个问题 谢谢！

**Comment by shaoniana1997** [comment]
之前做了一点，有什么问题嘛

**Comment by shaoniana1997** [comment]
你好，我最后只是把它当成了一个简单的分类任务，然后我用resnet模型+迁移训练在FI数据集进行训练的，效果还行。
（我用了FI八分类中的五个类别）

**Comment by JiachengDang** [comment]
明白了 谢谢
